import {
  Archive,
  Bell,
  ChartNoAxesColumn,
  FileText,
  GitBranch,
  FolderKanban,
  Gauge,
  Plug,
  Radar,
  Timer,
  TriangleAlert,
  UserCog,
  Users,
} from "lucide-react";

export const NAV_GROUPS = [
  {
    key: "operations",
    label: "Operação",
    items: [
      {
        key: "overview",
        label: "Dashboard",
        path: "/",
        icon: ChartNoAxesColumn,
        description: "Visão consolidada de compliance, auditoria e risco.",
        requiredAny: [],
      },
      {
        key: "compliance",
        label: "Compliance",
        path: "/compliance",
        icon: TriangleAlert,
        description: "Gestão de violações e ciclo de tratamento.",
        requiredAny: ["compliance.violations.read"],
      },
      {
        key: "compliance-sla",
        label: "SLA de Violações",
        path: "/compliance/sla",
        icon: Timer,
        description: "Monitoramento de prazo de tratamento por severidade.",
        requiredAny: ["compliance.violations.read"],
      },
      {
        key: "audit",
        label: "Auditoria",
        path: "/audit",
        icon: FolderKanban,
        description: "Consulta e investigação de trilhas de auditoria.",
        requiredAny: ["audit.logs.read.any", "audit.logs.read.scoped"],
      },
      {
        key: "risk",
        label: "Risco",
        path: "/risk",
        icon: Radar,
        description: "Análise de score de risco e histórico por tenant.",
        requiredAny: ["risk.scores.read"],
      },
    ],
  },
  {
    key: "governance",
    label: "Governança",
    items: [
      {
        key: "reports",
        label: "Relatórios",
        path: "/reports",
        icon: FileText,
        description: "Geração e exportação de relatórios operacionais.",
        requiredAny: ["reports.read", "reports.export"],
      },
      {
        key: "retention",
        label: "Retenção",
        path: "/retention",
        icon: Archive,
        description: "Políticas de retenção e arquivamento de dados.",
        requiredAny: ["audit.logs.read.any", "audit.logs.read.scoped", "compliance.violations.read"],
      },
      {
        key: "notifications",
        label: "Notificações",
        path: "/notifications",
        icon: Bell,
        description: "Configuração de canais e regras de notificação.",
        requiredAny: ["reports.read", "reports.export", "system.settings.manage"],
      },
      {
        key: "integrations",
        label: "Integrações",
        path: "/integrations",
        icon: Plug,
        description: "Gestão de integrações e conectores externos.",
        requiredAny: ["system.settings.manage"],
      },
      {
        key: "messaging",
        label: "Mensageria",
        path: "/messaging",
        icon: GitBranch,
        description: "Visualização ponta a ponta do fluxo de mensageria e falhas.",
        requiredAny: ["audit.logs.read.any", "audit.logs.read.scoped", "reports.read", "reports.export", "system.settings.manage"],
      },
    ],
  },
  {
    key: "system",
    label: "Sistema",
    items: [
      {
        key: "admin",
        label: "Administração",
        path: "/admin",
        icon: UserCog,
        description: "Gestão de usuários, permissões e controles administrativos.",
        requiredAny: ["users.read.any", "users.create", "roles.assign", "users.update", "users.deactivate", "system.settings.manage"],
      },
      {
        key: "teams",
        label: "Time",
        path: "/teams",
        icon: Users,
        description: "Visibilidade da estrutura de times e responsáveis.",
        requiredAny: [],
      },
      {
        key: "health",
        label: "Saúde",
        path: "/health",
        icon: Gauge,
        description: "Visão rápida da saúde geral da plataforma.",
        requiredAny: [],
      },
    ],
  },
];

export const NAV_ITEMS = NAV_GROUPS.flatMap((group) =>
  group.items.map((item) => ({
    ...item,
    groupKey: group.key,
    groupLabel: group.label,
  })),
);
