ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "failed_login_attempts" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "blocked_until" TIMESTAMP(3);
